name: Auto Tag on PR Merge (feature/PR-tagging)

on:
  pull_request:
    types: [closed]
    branches:
      - feature/PR-tagging

jobs:
  tag_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch All Tags
        run: git fetch --tags

      - name: Determine Version Bump from PR Label
        id: pr_info
        run: |
          echo "Extracting labels from PR..."
          labels="${{ toJson(github.event.pull_request.labels) }}"
          echo "PR labels: $labels"
          bump="patch"
          if echo "$labels" | grep -iq 'version:major'; then bump="major"; fi
          if echo "$labels" | grep -iq 'version:minor'; then bump="minor"; fi
          echo "Determined bump level: $bump"
          echo "::set-output name=bump::$bump"

      - name: Get Latest Tag
        id: latest_tag
        run: |
          latest=$(git tag --sort=-v:refname | grep '^release_candidate_' | head -n 1)
          echo "Latest tag: $latest"
          echo "::set-output name=tag::$latest"

      - name: Compute Next Tag
        id: next_tag
        run: |
          latest="${{ steps.latest_tag.outputs.tag }}"
          if [ -z "$latest" ]; then
            next="release_candidate_1.0.0"
          else
            version=${latest#"release_candidate_"}
            IFS='.' read -r major minor patch <<< "$version"
            case "${{ steps.pr_info.outputs.bump }}" in
              major) major=$((major + 1)); minor=0; patch=0;;
              minor) minor=$((minor + 1)); patch=0;;
              patch) patch=$((patch + 1));;
            esac
            next="release_candidate_${major}.${minor}.${patch}"
          fi
          echo "Next tag: $next"
          echo "::set-output name=tag::$next"

      - name: Create Git Tag
        run: |
          git config user.name "Poojakagale"
          git config user.email "poojankagale1996@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/Poojakagale/node-todo-cicd.git
          git tag ${{ steps.next_tag.outputs.tag }}
          git push origin ${{ steps.next_tag.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.tag }}
          name: ${{ steps.next_tag.outputs.tag }}
          body: "Automated release for feature/PR-tagging branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
